### ISSUE TITLE
Part 2 - Error on 6_scoreImage

### ISSUE THREAD

**Issue by jpbgameiro** [Azure/ObjectDetectionUsingCntk#22]
I tried to follow the toturial but I am having trouble getting it to work.

Regarding PART2 (where I have changed the classifier to 'nn'), I executed steps 1, 2, and 3 ok and after 40 to 50 minutes later I had my .model file. But when I execute 6_scoreImage on an image to try out the model, it is giving me the following error:

**2017-08-04 08:08:22
PARAMETERS: datasetName = grocery
Loading DNN..
Time loading DNN [ms]: 58088.543
Calling selective search..
   Number of rois detected using selective search: 1350
   Number of rois on grid added: 3295
   Number of ROIs before filtering  = 4645
   Number of ROIs after filtering  = 3812
Time roi computation [ms]: 4639.621
Time cnkt input generation [ms]: 125.002
Running model..
Time running model [ms]: 6329.613
Traceback (most recent call last):
  File "6_scoreImage.py", line 77, in <module>
    decisionThreshold = vis_decisionThresholds[classifier])
  File "C:\Users\gameiro\Documents\ObjRecon\helpers.py", line 445, in scoreRois
    svmWeights, svmBias, svmFeatScale)
  File "C:\Users\gameiro\Documents\ObjRecon\helpers.py", line 426, in scoreRoi
    scores = softmax(dnnOutput)
  File "C:\Users\gameiro\Documents\ObjRecon\helpers.py", line 922, in softmax
    if max(expVec) == np.inf:
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()**

 I didn't change anything besides the clasiffier='nn' and the image location, do I need to add anything ele? Don't know what I could me missing.

**Comment by pamio** [comment]
Which CNTK version are you using ? I had to use CNTK 2 RC1 to be able to run this successfully. Encountered the same issue with other versions.

**Comment by jpbgameiro** [comment]
I have CNTK 2 but how do I know if it's RC1 or another? I created a Data Science Virtual Machine for Windows. If I have another version, can I simply uninstall the CNTK I have installed and install CNTK 2 RC 1?

**Comment by pamio** [comment]
I didn't uninstall anything but created a new folder and installed CNTK RC1 with anaconda there. And used used cntkpy35.bat file from the respective folder to activate the env.  You could follow instructions on how to install CNTK2 rc1 [here](https://docs.microsoft.com/en-us/cognitive-toolkit/setup-windows-python?tabs=cntkpy20#anaconda3)

**Comment by jpbgameiro** [comment]
Hi @pamio, I have installed CNTK 2 RC 1 as you said, activated the env cntk-py35, an verified the cntk version:

> (cntk-py35) C:\Windows\system32>python -c "import cntk; print(cntk.__version__)"
> 2.0rc1

But after executing steps 1, 2 and 3 with success, I then try executing executing 6_scoreImage and the exact same error occurs that I mentioned in my first comment. 
I also tried following the steps in Part1 (with classifier = 'svm') but it returns an error also on 4_trainSvm.py.
Is this being caused my an incorrect creation of my model on the first steps? Were you able to execute all the steps without any other changes? 

Thanks for the help.

**Comment by jpbgameiro** [comment]
I managed to get the script 6_scoreImage working, I just added Line 2 to the helpers.py:

```
Line 1: def scoreRois(classifier, dnnOutputs, svmWeights, svmBias, svmFeatScale, roiDim, decisionThreshold = None):
Line 2:    dnnOutputs = dnnOutputs[0]
Line 3:    roiSize = dnnOutputs.shape[0]
...
```
Don't know why yet, but it was adding the ROI matrix to another array..
