### ISSUE TITLE
Error in 3_runCntk.py

### ISSUE THREAD

**Issue by guangying94** [Azure/ObjectDetectionUsingCntk#27]
Hi, I followed the sequences shown in documentation, but I faced this error when I tried to execute 3_runCntk.py. After it loaded pre-trained model, this is the error I received. 

Traceback (most recent call last):
  File "3_runCntk.py", line 20, in <module>
    cntk_lr_per_image, cntk_l2_reg_weight, cntk_momentum_time_constant, cntkFilesDir, boSkipTraining)
  File "D:\Marcus\CNTK\ObjectDetectionUsingCntk\helpers_cntk.py", line 102, in init_train_fast_rcnn
    frcn_output, frcn_penultimateLayer = frcn_predictor(image_input, roi_input, num_classes, base_path)
  File "D:\Marcus\CNTK\ObjectDetectionUsingCntk\helpers_cntk.py", line 77, in frcn_predictor
    roi_out   = roipooling(conv_out, rois, (roi_dim, roi_dim))
  File "D:\Marcus\CNTK\Anaconda3\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
    result = f(*args, **kwds)
TypeError: roipooling() missing 2 required positional arguments: 'roi_output_shape' and 'spatial_scale'

How do I generate the required arguments?

**Comment by bpatil16** [comment]
I get the same errors any clue on how to generate these arguments

**Comment by PatrickBue** [comment]
Hi, what version of CNTK are you using? This might be due to breaking changes in version 2.2. Try 2.0 and this should hopefully fix this error.

**Comment by kpierce8** [comment]
Any hints on how to change the 2.2 scripts to work? I just spent hours getting CNTK set up on my machine and all the install information is now for 2.2.
