### ISSUE TITLE
ERROR: Python version sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0) not supported

### ISSUE THREAD

**Issue by codeslord** [Azure/ObjectDetectionUsingCntk#36]
I am getting the following error while running 2_cntkGenerateInputs.py

python 2_cntkGenerateInputs.py
ERROR: Python version sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0) not supported
--------------------------------------------------------------
2018-07-11 11:26:07
PARAMETERS: datasetName = screenshots
Number of images in set 'train' = 51
Processing image set 'train', image 0 of 51
wrote gt roidb to D:\Users\rohit\nemesis\ObjectDetection/proc/screenshots/cntkFiles/train.cache_gt_roidb.pkl
Traceback (most recent call last):
  File "2_cntkGenerateInputs.py", line 46, in <module>
    currRois = imdb.roidb[imgIndex]['boxes']
  File "D:\Users\rohit\nemesis\ObjectDetection\fastRCNN\imdb.py", line 72, in roidb
    self._roidb = self.roidb_handler()
  File "D:\Users\rohit\nemesis\ObjectDetection\imdb_data.py", line 108, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "D:\Users\rohit\nemesis\ObjectDetection\imdb_data.py", line 141, in _load_selective_search_roidb
    return self.create_roidb_from_box_list(box_list, gt_roidb)
  File "D:\Users\rohit\nemesis\ObjectDetection\fastRCNN\imdb.py", line 176, in create_roidb_from_box_list
    gt_overlaps = bbox_overlaps(boxes.astype(np.float),
NameError: name 'bbox_overlaps' is not defined

**Comment by codeslord** [comment]
Compiled cython_bbox for python 3.6 and the issue is resolved
