### ISSUE TITLE
No module named cython_bbox

### ISSUE THREAD

**Issue by AkshayAgarwal007** [Azure/ObjectDetectionUsingCntk#4]
I am trying this out on Azure Linux Data Science VM. I am getting the following error when I am executing the A1_annotateImages.py file.

Traceback (most recent call last):
  File "A1_annotateImages.py", line 2, in <module>
    import PARAMETERS
  File "/home/AkshayAgarwal007/Desktop/detection/PARAMETERS.py", line 1, in <module>
    from cntk_helpers import *
  File "/home/AkshayAgarwal007/Desktop/detection/cntk_helpers.py", line 5, in <module>
    from fastRCNN.nms import nms as nmsPython
  File "/home/AkshayAgarwal007/Desktop/detection/fastRCNN/__init__.py", line 7, in <module>
    from .imdb import imdb
  File "/home/AkshayAgarwal007/Desktop/detection/fastRCNN/imdb.py", line 15, in <module>
    from utils_compiled64bit.cython_bbox import bbox_overlaps
ImportError: No module named cython_bbox

Seems to be an import issue with .pyd file. How to resolve this?

**Comment by PatrickBue** [comment]
You are getting this error since the 'cython_bbox' binaries are compiled for windows. A quick fix would be to switch to a VM which runs windows. Alternately, you could install and compile for Linux yourself. See the original fast R-CNN code for that, e.g. https://github.com/rbgirshick/fast-rcnn/tree/master/lib/utils

**Comment by AkshayAgarwal007** [comment]
Thanks. I am using the Azure Windows Data Science VM now. It's working fine.
